### ISSUE TITLE
yaml kubernetes schemas not working/not able to set custom schema

### ISSUE THREAD

**Issue by szechp** [AstroNvim/AstroNvim#2066]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macos 13.3.1

### Terminal/GUI

iterm

### AstroNvim Health

==============================================================================
astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v3.29.4
- Neovim Version: v0.9.1
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python3` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

i used a virgin astronvim for this:
*yamlls* and *yaml ts* is installed. I open the following yaml:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: some-app
  namespace: some-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: some-app
  template:
    metadata:
      labels:
        app: some-app
    spec:
      containers:
        - name: some-app
          image: git.myinstance.com:1234/repo/some-app:latest
          args: ["java", "-jar", "/home/app/some-app.jar"]
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: registry-credentials-some-app
```

i get no autocomplete or autoindendation:
<img width="625" alt="Screenshot 2023-06-29 at 15 41 28" src="https://github.com/AstroNvim/AstroNvim/assets/45265588/9b034db8-5e6f-4492-906d-cd60dbd8122f">

i have the same behavior when i add my own yaml schema:
`user/init.lua`:
```
return {

  lsp = {
        ["server-settings"] = {
      -- example for addings schemas to yamlls
      yamlls = { -- override table for require("lspconfig").yamlls.setup({...})
        settings = {
          yaml = {
            schemas = {
              ["/Users/myuser/k8s1.27.2.json"] = "*.{yaml,yml}",
            },
          },
        },
        filetypes = { "yaml.k8s" },
      },
    },
  },
}
```

but when i define a custom file-type and use it to attach a custom lsp it works:
<img width="589" alt="Screenshot 2023-06-29 at 15 58 12" src="https://github.com/AstroNvim/AstroNvim/assets/45265588/929b0fd6-3805-46d1-9a10-e84c41fcea10">

changed `user/init.lua` with custom lsp and filetype (note: anything else like lsp customization is removed):
```
return {
  polish = function()
  
      local function yaml_ft(path, bufnr)
      -- get content of buffer as string
      local content = vim.filetype.getlines(bufnr)
      if type(content) == "table" then content = table.concat(content, "\n") end

      -- check for Kubernetes specific properties
      -- Look for 'apiVersion', 'kind', 'metadata', 'spec' all in the same file
      local k8s_regex = vim.regex "apiVersion:.*kind:.*metadata:.*spec:"
      if k8s_regex and k8s_regex:match_str(content) then return "yaml.k8s" end

      -- return yaml if nothing else
      return "yaml"
    end
    vim.filetype.add {
      extension = {
        yml = yaml_ft,
        yaml = yaml_ft,
      },
    }

    function setup_k8s_lsp()
      require("lspconfig").yamlls.setup {
        cmd = { "/opt/homebrew/bin/node", "/Users/myuser/.local/share/nvim/mason/bin/yaml-language-server", "--stdio" },
        settings = {
          yaml = {
            schemas = {
              ["/Users/myuser/k8s1.27.2.json"] = "/*.{yaml,yml}",
            },
          },
        },
        filetypes = { "yaml.k8s" },
      }
    end

    vim.cmd [[ autocmd FileType yaml.k8s lua setup_k8s_lsp() ]]
  end,
}

```
but then i get the error:
```
Error executing vim.schedule lua callback: UnhandledPromiseRejection with the reason:
RPC[Error] code_name = InternalError, message = "Request textDocument/foldingRange failed with message: Cannot read properties of undefined (reading 'lineFoldingOnly')"
```
i can fix this error by disabling the ufo plugin.

*conclusion*: is it possible that lsp ["server-settings"] is not working correctly? the custom schema is not recognized.

(heres the json file I'm using, rename to .json when using, gitlab wont let me upload json: 
[k8s1.27.2.txt](https://github.com/AstroNvim/AstroNvim/files/11906634/k8s1.27.2.txt))

note: i initially thought this was a problem with yamlls and macos, but this is not true https://github.com/AstroNvim/AstroNvim/issues/1952
### Steps to Reproduce

i think i thoroughly described this above :)

### Expected behavior

it would be great if the k8s schema can be provided out of the box. if not it would be great if i was able to define my own custom schemas they way it is intended and documented.
